### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by LasaleFamine** [LasaleFamine/ragusabot#6]

**Comment by anshuman73** [comment]
Hi, I'd like to work on this.
Any special instructions you'd like to have ?

**Comment by LasaleFamine** [comment]
Hi @anshuman73, thank you for you interest.
I think the only thing is that I want to maintain the `master` as a production-ready ready branch, so no PR on it.

**Comment by anshuman73** [comment]
Alright !
will send a PR in a while :)
